### ISSUE TITLE
Sidebar icons hidden by hosting page CSS

### ISSUE THREAD

**Issue by webwelten** [hypothesis/h#1848]
Apparently, the sidebar html gets partly overwritten or somehow influenced on specific websites.

Try it on:
http://speakingjs.com/es5/ch14.html

![bildschirmfoto 2015-01-13 um 13 14 40](https://cloud.githubusercontent.com/assets/3693161/5720717/68288432-9b28-11e4-9dd8-d9d959a0ddfa.png)
- Action buttons are almost hidden under the sidebar and inaccessible.
  - First toggle button doesn't work. You have to pull the sidebar into the site manually with the cursor.

**Comment by webwelten** [comment]
So, I detected some css code in the site's core.css which causes the behaviour. It influences the <ul> in <div class=".annotator-toolbar"> overwriting it's margin with !important.

```css
ul { 
  list-style-type: square;
  margin-top: 8px !important;
  margin-bottom: 8px !important;
  margin-left: 5px !important;
  padding-left: 20px !important;
}
```

**Comment by tilgovi** [comment]
Thanks for the report. I think we should probably move the toolbar inside the iframe, so it's isolated from these things.

**Comment by dwhly** [comment]
Would that have any design implications?

**Comment by csillag** [comment]
No. It used to be there; looked the same.
2015.01.14. 10:49 ezt írta ("Dan Whaley" <notifications@github.com>):

**Comment by tilgovi** [comment]
Coming from this CSS:

```css
ul {
  list-style-type: square;
  margin-top: 8px !important;
  margin-bottom: 8px !important;
  margin-left: 5px !important;
  padding-left: 20px !important;
}
```
