### ISSUE TITLE
Adder doesn't show properly on ESPN.com

### ISSUE THREAD

**Issue by dwhly** [hypothesis/h#3192]
### Steps to reproduce
1. With Chrome extension
2. Go here: http://espn.go.com/nba/story/_/id/15159766/golden-state-warriors-coach-steve-kerr-inclined-rest-players-talk-team-first
   3 Make a selection
### Expected behaviour

Adder should show
### Actual behaviour

It doesn't
### Additional details

Luckily since the page note feature is now responsive to selections, you can click the icon and still create an annotation on the selection regardless.  But we should fix the adder problem if possible.

**Comment by nickstenning** [comment]
Had a quick look into this and the problem is that the page declares a huge z-index on the main body container element:

```CSS
#global-viewport #pane-main {
    background: #f1f2f3;
    position: relative;
    width: 100%;
    z-index: 1000006;
}
```

I'm going to close this as a duplicate of that issue.
