### ISSUE TITLE
No admin User

### ISSUE THREAD

**Issue by Goddywu** [hypothesis/h#6014]
I have use docker-compose.yml：

```
version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
  elasticsearch:
    image: hypothesis/elasticsearch:latest
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
  web:
    image: hypothesis/hypothesis:latest
    environment: 
      - APP_URL=http://localhost:5000
      - AUTHORITY=localhost
      - BROKER_URL=amqp://guest:guest@rabbit:5672//
      - CLIENT_OAUTH_ID
      - CLIENT_URL=http://localhost:3001/hypothesis
      - DATABASE_URL=postgresql://postgres@postgres/postgres
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NEW_RELIC_APP_NAME=h (dev)
      - NEW_RELIC_LICENSE_KEY
      - SECRET_KEY=notasecret
    ports: 
      - '5000:5000'
    depends_on: 
      - postgres
      - elasticsearch
      - rabbit
```
and then I init db

```
docker-compose exec web /bin/sh

hypothesis init
```

however, when I visit http://localhost:5000, I have no account to login as admin.

I have seen this doc https://h.readthedocs.io/en/latest/developing/administration/ . However, it is not suit for my docker-compose.yml.
